[env]
K6_NO_USAGE_REPORT = "true"

[tools]
hurl = "8.0.1"
k6 = "2.2.0"

[tasks.hurlfmt-check]
run = "hurlfmt --check hurl/*.hurl"

[tasks.hurl]
run = "./hurl/run.sh"

[tasks.k6-load]
run = "./k6/run.sh k6/load.js"

[tasks.k6-etag]
run = "./k6/run.sh k6/etag.js"

[tasks.k6-benchmark]
run = "./k6/run.sh k6/benchmark.js"

[tasks.k6-range]
run = "./k6/run.sh k6/range.js"

[tasks.k6-query]
run = "./k6/run.sh k6/query.js"

[tasks.k6]
depends = ["k6-load", "k6-etag", "k6-benchmark", "k6-range", "k6-query"]

[tasks.check]
depends = ["hurlfmt-check", "hurl"]
